services:
  db:
    image: postgres:11.15-bullseye
    command:  postgres -c 'max_connections=50'
    volumes:
      - postgres-data:/var/lib/postgresql
      - ./db/pginit.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: ifuture
    networks:
      - ifuture
    deploy:
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 1536M
networks:
  ifuture:
    driver: bridge

volumes:
  postgres-data:
    external: false